### ISSUE TITLE
"You uploaded an HDR video, but the pixel format is incorrect"

### ISSUE THREAD

**Issue by zmarty** [YouTubeHDR/hdr_metadata#11]
While I upload HDR videos I see this less than helpful message on the YouTube website:

> You uploaded an HDR video, but the pixel format is incorrect. For more information on best practices for creating HDR content please refer to [this](**https://support.google.com/youtube/answer/7126552?hl=en**) article.

The [article](https://support.google.com/youtube/answer/7126552?hl=en) does not say anything about "pixel format". Can you be a bit more specific?

**Comment by nbirkbeck** [comment]
Can you share an example video id?

The message is referring to the pixel format needing to be at least 10-bit.

**Comment by zmarty** [comment]
Here is one example: https://www.youtube.com/watch?v=74SZXCQb44s

This is 10 bit video in a 12 bit DNxHR HQX format.

**Comment by nbirkbeck** [comment]
Thanks for sharing the video and for filing the bug report! 

The warning definitely should not have shown up on the video. The problem has been fixed. I'll file a request to get the help text updated.

**Comment by zmarty** [comment]
Thanks! Please close this item once it's fixed. Also, it would be great if you guys could take a look at the other open items.

**Comment by TruVetCommando** [comment]
I get the same problem does the video come out in HDR in the end?

**Comment by nbirkbeck** [comment]
@TruVetCommando can you please share a video id?

**Comment by TruVetCommando** [comment]
It is still processing at the moment 

https://youtu.be/8R_aST3LzHM

**Comment by nbirkbeck** [comment]
I'm seeing the pixel format of yuv420p on that video (meanin it is bit depth=8). YouTube won't recognize it as HDR unless it is higher bit depth (>= 10). You will need to use an HDR10 profile.

**Comment by TruVetCommando** [comment]
so when I use mvkmerge to convert from h265 hevc ( xboxonex direct capture from console ) to mvk its dropping the bit depth?

**Comment by TruVetCommando** [comment]
can sony vegas 15 produce the required pixel format required?

**Comment by TruVetCommando** [comment]
![image](https://user-images.githubusercontent.com/36688894/36495860-877c19fe-172e-11e8-8d97-b2e9c3af4828.png)
 this is the original capture from the xbox

**Comment by nbirkbeck** [comment]
mkvmerge is just transmuxing (it doesn't touch the underlying elementary encoded bitstream). The issue with using a source that is 8-bit in HDR is the presence of banding (visibly observable bands between even the nearest gray level codes in the video)--and this is why YouTube won't respect an 8-bit file marked with HDR transfer functions.

I haven't used Sony Vegas, but I imagine it can manipulate higher bit depth video (again, the problem is going to be that the original source bit depth is too low). Another option for editing/coloring is Davinci  Resolve (I think there is a free version).
